### ISSUE TITLE
Run CSS and HTML through validator 

### ISSUE THREAD

**Issue by catheraaine** [sparkbox/lamppost#199]
https://validator.w3.org/

**Comment by boomingbrake** [comment]
![screen shot 2016-06-17 at 11 04 11 am](https://cloud.githubusercontent.com/assets/7769408/16155012/65ab62fe-347b-11e6-8c91-bed3e52f74b8.png)

**Comment by boomingbrake** [comment]
@iAmNathanJ @catheraaine @BC3209 

Basically 2 errors (events cause repeat of same) .
Nate said the first is bogus.

The other issue: is the site logo.  We have a div in an a tag

**Comment by boomingbrake** [comment]
CSS Validation
![screen shot 2016-06-17 at 1 38 14 pm](https://cloud.githubusercontent.com/assets/7769408/16159455/dae9aa98-3490-11e6-925a-a5d4bd208e80.png)
