### ISSUE TITLE
Documentation Improvements

### ISSUE THREAD

**Issue by catheraaine** [sparkbox/lamppost#267]
Documentation needs updated and reorganized. Direct main README at developers who want to set up their own Lamppost .

Add:
- [x] Synopsis / Motivation
- [x] Deploy to Heroku Button
- [x] Theming
- [x] Environment Setup
- [x] Contributing

**Comment by iAmNathanJ** [comment]
@catheraaine I just created this same card. Didn't realize you had done it! I'll close mine. I added some todos to this one. Do you mind if I scaffold the changes out? And then we can work through making it right?
