### ISSUE TITLE
Setting up Lampposts in other cities

### ISSUE THREAD

**Issue by iAmNathanJ** [sparkbox/lamppost#269]
@cromwellryan @drewclemens

Would love some feedback on this.

I like the idea of others setting up a Lamppost for themselves. I think there is some work to do in making that process accessible and as simple as possible.

Adding a deploy to Heroku button is a great idea. Click a button, fill out admin credentials, city name, contact email, etc and a new lamppost will be up in a couple minutes. That's really easy and could be done without touching code. But because our current production deployment is tied to our database and running our review apps, there is a conflict.

Things I *think* need to be done:
- The public lamppost repo should be a generic version of the app. Clone-able, single click Heroku, or deployable in any manner of choice. This could continue to be developed using review apps with placeholder data. Heroku discourages running review apps on production sites.
- Our production app should be in a separate, private repo and should be a clone of the generic app.
- Some of the site content needs to be separated into partials or environment variables. I'm thinking `ADMIN_EMAIL` (for submissions) and/or `CITY`.
- The content of the about section should be a partial and customizable per deployment. I think this a hard problem (assuming the use of Heroku button) unless people are instructed to fork the repo and then press the button.
- Another challenge is the font CDN we are using. We can't whitelist every domain for that resource. Something to think about. Should we verify new installations of lamppost and setup subdomains on lamppost.io as they come? That could solve the problem, but there are probably other solutions.

I'm sure there's more that I'm not thinking of at the moment. This is just what came up as I've been working over our documentation. Do we have time to tackle this and really make this something that others can use? I'd like to make it happen, but I'm hesitant to move forward until I hear what you all have to say.

I have a fork with a README update in progress here -  https://github.com/iAmNathanJ/lamppost/blob/master/README.md

**Comment by drewclemens** [comment]
I think these are all really good points. Good thinking.

My suggestion would be to add some of these thoughts to the readme. Be upfront about these limitations and the refactoring that would need to be done. Make the tone such that we welcome people forking the repo, but at the same time we're acknowledging that it is less than optimized for it at this time. Point out some of these known issues (create issues for them too) to better prepare a potential fork.

That's the first thing I'd do so that the docs reflect reality immediately. Then we can work on prioritizing the tasks and knocking them out... with the understanding that it may take awhile because this project will soon become a secondary priority and no longer your first priority.

Agreed @cromwellryan ?

**Comment by drewclemens** [comment]
@iAmNathanJ I've made this "issue" into an "epic." That just means that it represents a lot of smaller issues/stories inside of it. I'd suggest creating good issues that fit under this epic, and then you can add those issues to this epic. It will allow anyone viewing the public repo to see the progress required and progress made toward this repo becoming more portable for other cities.

**Comment by iAmNathanJ** [comment]
@drewclemens Awesome, this all makes sense. Helps me underestand what to do with the docs at this point. I'll open the issues and update the README with all of this in mind. Thanks. 😄

**Comment by iAmNathanJ** [comment]
@catheraaine See above.

**Comment by cromwellryan** [comment]
I'm super happy about the the documentation that would go along with the Deploy to Heroku button.
