### ISSUE TITLE
Theme-ability

### ISSUE THREAD

**Issue by iAmNathanJ** [sparkbox/lamppost#275]
The site is currently Theme-able with a single color.
Would be nice to make the default scheme monochrome, like the initial design, but maybe setup for possible multi color theming?

Regardless, we'll need to split off the sass theme partial so it doesn't get pulled into the site be default. And we'll need to cover theming in the README.

**Comment by catheraaine** [comment]
>  split off the sass theme partial so it doesn't get pulled into the site be default. 

What do you mean?

**Comment by iAmNathanJ** [comment]
@catheraaine, don't worry about that for now. We can talk about it when I'm in the office. I guess we just want to do a light and dark theme for now?
