### ISSUE TITLE
Manage Site Performance

### ISSUE THREAD

**Issue by drewclemens** [sparkbox/lamppost#6]
Dependent on #3 because we need Heroku to run and provide a URL to test.

* [ ] determine performance budget
* [ ] write script to run webpage test and compare results to budget
* [ ] documentation

Consider Speed Curve (paid service) as an alternative to Webpage Test if needed.

**Comment by cromwellryan** [comment]
@drewclemens I'm happy to close this for the time being. We don't have a nice way to solve this problem in the immediate term, but the team has gotten things to a great spot. Managing it going forward is going to be manual. ¯\_(ツ)_/¯
